### ISSUE TITLE
Страница коллекций

### ISSUE THREAD

**Issue by KozlovKV** [FIT-2024-RecALL/recall-front#15]
- [x] Сделать наполнение для страницы коллекций (роут `/collections`), опираясь на дизайн в фигме
- [ ] Создать слайс стэйта для списка коллекций и добавить его в общий стэйт. С слайсе должны быть
  - [x] Список коллекций (*поля пока что выдумай сам*)
  - [ ] Функция запроса стэйтов с бэка
  - *возможно что-то ещё*

**Comment by MelloTheCatLover** [comment]
Начал разрабоотку страниц коллекций. Понял как работает wouter и как ты стрницы генеришь. Чуть исправил футер, чтобы он на всех страницах норм отображался. 

План действий:
1. Компонент карточки
2. Стилизация
3. Добавление карточик(Пока не знаю как запрашивать или отдавать что-то в бек(на практике) 
4. Сайд бар
тут уже доп
5. Поиск коллекций(Elasctic Search)

**Comment by KozlovKV** [comment]
> Начал разрабоотку страниц коллекций. Понял как работает wouter и как ты стрницы генеришь. Чуть исправил футер, чтобы он на всех страницах норм отображался.
> 
> План действий:
> 
> 1. Компонент карточки
> 2. Стилизация
> 3. Добавление карточик(Пока не знаю как запрашивать или отдавать что-то в бек(на практике)
> 4. Сайд бар
>    тут уже доп
> 5. Поиск коллекций(Elasctic Search)

Карточка - отдельная объёмная задача. Для неё я сделал отдельную таску - #16 . Равно как и добавление карточек будет следующей из неё задачей

Твоя первоначальная задача - это именно страница с коллекциями, то есть сайдбар и список коллекций + кнопки на этих коллекциях, которые будут новыми роутами

Elastic search? Ты знаешь, как с ним работать? Я просто пока ничего с ним не делал

**Comment by MelloTheCatLover** [comment]
Про карточку понял. Ты эту задачу уже взял. Я посмотрел на ветке. Ты пока что просто компонент создал?

**Comment by KozlovKV** [comment]
> Про карточку понял. Ты эту задачу уже взял. Я посмотрел на ветке. Ты пока что просто компонент создал?

Да, совсем базовый. Там ещё много чего надо накручивать

**Comment by MelloTheCatLover** [comment]
Я про компонент коллекции. Она просто тоже ка ккарточка выглядит. Забей. 

Я про коллекции. Я их карточками обозвал

**Comment by KozlovKV** [comment]
А, понял. Ну... это тоже контейнер, однако у него нет функции всплытия и есть кнопки, так что разница всё же есть

**Comment by KozlovKV** [comment]
Редактирование коллекции уже даже не в самом зачаточном виде у нас есть. Сейчас волью его в develop, поэтому ссылку по кнопке редактирования можешь делать уже рабочей

**Comment by KozlovKV** [comment]
Влил штуки по редактированию коллекции и карточек. Не забудь прописать git pull, а потом влей develop в свою ветку

**Comment by KozlovKV** [comment]
Ещё кое-какие интересные штуки записал по поводу стилей с использованием `display: grid` на [вики](https://github.com/FIT-2024-RecALL/recall-front/wiki/CSS)

**Comment by MelloTheCatLover** [comment]
Добавил отображение коллекций на странице, подогнал его под оформление, естественно модификация продолжится далее. Добавил элемент поиска, у которого уже есть нормальное дополнение поиска по именам коллекций, но что-то мне подсказывает, что так делать не надо. Сейчас это просто список коллекций. Нужно будет разобраться с запросом данных с бека. Данных колеекций, их имен и тд тп. 

В поиске добавил возможность навигации по кнопкам, это круто, мне нравится))
Коллекции вроде нормально отображаются

продолжу совершенствоваться. Нужно еще по коду мне пройтись, он стал чуть громоздким и результаты поиска отображаются одновременно с всплывающим окном, оставлю окно, а результат отображу после того как поиск завершен

**Comment by KozlovKV** [comment]
> Добавил отображение коллекций на странице, подогнал его под оформление, естественно модификация продолжится далее. Добавил элемент поиска, у которого уже есть нормальное дополнение поиска по именам коллекций, но что-то мне подсказывает, что так делать не надо. Сейчас это просто список коллекций. Нужно будет разобраться с запросом данных с бека. Данных колеекций, их имен и тд тп.
> 
> В поиске добавил возможность навигации по кнопкам, это круто, мне нравится)) Коллекции вроде нормально отображаются
> 
> продолжу совершенствоваться. Нужно еще по коду мне пройтись, он стал чуть громоздким и результаты поиска отображаются одновременно с всплывающим окном, оставлю окно, а результат отображу после того как поиск завершен

Супер! Оформи pull request в develop, чтобы можно было посмотреть

**Comment by MelloTheCatLover** [comment]
Доделал страницу коллекций по всем правкам. На гите ждет апрува
