### ISSUE TITLE
Составить базовый UI

### ISSUE THREAD

**Issue by KozlovKV** [FIT-2024-RecALL/recall-front#5]
- [x] Опираясь на требования из юз-кейсов в SRS, составить базовый каркас юзер-интерфейса
  - **Учитывать, что дизайн должен быть адаптивным**
  - Для базового наброска, использовать [TLDraw](https://www.tldraw.com/), затем можно Фигму
- [ ] Сохранить артефакты в папке на [Гугл диске](https://drive.google.com/drive/u/0/folders/1Z9ssZwz_8hgpyotrpttpYv88Nh6lVeyY)

**Comment by KozlovKV** [comment]
Ссылка на SRS - https://docs.google.com/document/d/1MfSeU5wc_RzUY5g6wgfFbJI7ETCF91yx8yBFhWS3xbs/edit#heading=h.ok59cpyp4hdh

**Comment by MelloTheCatLover** [comment]
Сделал дизайн основной страницы в фигме. Цвета/Шрифт/Понимание лайоутов сайта для все страниц.

**Comment by MelloTheCatLover** [comment]
https://www.figma.com/design/9jFCW0gJYExc58LHrMWpX2/Untitled?node-id=18-80&t=RmKbsIrymccsGqdc-1

**Comment by KozlovKV** [comment]
@MelloTheCatLover , сохрани скрины из Фигмы на гугл диске, далее переведи таск в Done и создай новые отдельные таски для больших кусков дизайна. Надо понижать объёмность каждого отдельного таска
